# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeatMap_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeatMap_Dialog(object):
    def setupUi(self, SeatMap_Dialog):
        SeatMap_Dialog.setObjectName("SeatMap_Dialog")
        SeatMap_Dialog.resize(308, 394)
        self.lineB_Label_2 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineB_Label_2.setGeometry(QtCore.QRect(20, 190, 21, 20))
        self.lineB_Label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineB_Label_2.setObjectName("lineB_Label_2")
        self.B5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B5_PushButton.setGeometry(QtCore.QRect(210, 190, 31, 31))
        self.B5_PushButton.setText("")
        self.B5_PushButton.setCheckable(True)
        self.B5_PushButton.setAutoDefault(False)
        self.B5_PushButton.setObjectName("B5_PushButton")
        self.buttonGroup = QtWidgets.QButtonGroup(SeatMap_Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.B5_PushButton)
        self.D1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D1_PushButton.setGeometry(QtCore.QRect(40, 90, 31, 31))
        self.D1_PushButton.setText("")
        self.D1_PushButton.setAutoDefault(False)
        self.D1_PushButton.setObjectName("D1_PushButton")
        self.buttonGroup.addButton(self.D1_PushButton)
        self.E5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E5_PushButton.setGeometry(QtCore.QRect(210, 40, 31, 31))
        self.E5_PushButton.setText("")
        self.E5_PushButton.setCheckable(True)
        self.E5_PushButton.setAutoDefault(False)
        self.E5_PushButton.setObjectName("E5_PushButton")
        self.buttonGroup.addButton(self.E5_PushButton)
        self.A6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A6_PushButton.setGeometry(QtCore.QRect(250, 240, 31, 31))
        self.A6_PushButton.setText("")
        self.A6_PushButton.setCheckable(True)
        self.A6_PushButton.setAutoDefault(False)
        self.A6_PushButton.setObjectName("A6_PushButton")
        self.buttonGroup.addButton(self.A6_PushButton)
        self.lineE_Label_2 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineE_Label_2.setGeometry(QtCore.QRect(20, 40, 21, 20))
        self.lineE_Label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineE_Label_2.setObjectName("lineE_Label_2")
        self.C1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C1_PushButton.setGeometry(QtCore.QRect(40, 140, 31, 31))
        self.C1_PushButton.setText("")
        self.C1_PushButton.setAutoDefault(False)
        self.C1_PushButton.setObjectName("C1_PushButton")
        self.buttonGroup.addButton(self.C1_PushButton)
        self.lineD_Label_4 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineD_Label_4.setGeometry(QtCore.QRect(20, 90, 21, 20))
        self.lineD_Label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineD_Label_4.setObjectName("lineD_Label_4")
        self.row5_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row5_Label.setGeometry(QtCore.QRect(220, 10, 21, 20))
        self.row5_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row5_Label.setObjectName("row5_Label")
        self.row4_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row4_Label.setGeometry(QtCore.QRect(180, 10, 21, 20))
        self.row4_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row4_Label.setObjectName("row4_Label")
        self.lineC_Label_3 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineC_Label_3.setGeometry(QtCore.QRect(20, 140, 21, 20))
        self.lineC_Label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineC_Label_3.setObjectName("lineC_Label_3")
        self.Continue_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.Continue_PushButton.setGeometry(QtCore.QRect(50, 350, 81, 31))
        self.Continue_PushButton.setObjectName("Continue_PushButton")
        self.C2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C2_PushButton.setGeometry(QtCore.QRect(80, 140, 31, 31))
        self.C2_PushButton.setText("")
        self.C2_PushButton.setCheckable(True)
        self.C2_PushButton.setAutoDefault(False)
        self.C2_PushButton.setObjectName("C2_PushButton")
        self.buttonGroup.addButton(self.C2_PushButton)
        self.row3_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row3_Label.setGeometry(QtCore.QRect(130, 10, 21, 20))
        self.row3_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row3_Label.setObjectName("row3_Label")
        self.A3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A3_PushButton.setGeometry(QtCore.QRect(120, 240, 31, 31))
        self.A3_PushButton.setText("")
        self.A3_PushButton.setCheckable(True)
        self.A3_PushButton.setAutoDefault(False)
        self.A3_PushButton.setObjectName("A3_PushButton")
        self.buttonGroup.addButton(self.A3_PushButton)
        self.row2_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row2_Label.setGeometry(QtCore.QRect(90, 10, 21, 20))
        self.row2_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row2_Label.setObjectName("row2_Label")
        self.A4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A4_PushButton.setGeometry(QtCore.QRect(170, 240, 31, 31))
        self.A4_PushButton.setText("")
        self.A4_PushButton.setCheckable(True)
        self.A4_PushButton.setAutoDefault(False)
        self.A4_PushButton.setObjectName("A4_PushButton")
        self.buttonGroup.addButton(self.A4_PushButton)
        self.C3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C3_PushButton.setGeometry(QtCore.QRect(120, 140, 31, 31))
        self.C3_PushButton.setText("")
        self.C3_PushButton.setCheckable(True)
        self.C3_PushButton.setAutoDefault(False)
        self.C3_PushButton.setObjectName("C3_PushButton")
        self.buttonGroup.addButton(self.C3_PushButton)
        self.B1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B1_PushButton.setGeometry(QtCore.QRect(40, 190, 31, 31))
        self.B1_PushButton.setText("")
        self.B1_PushButton.setCheckable(True)
        self.B1_PushButton.setAutoDefault(False)
        self.B1_PushButton.setObjectName("B1_PushButton")
        self.buttonGroup.addButton(self.B1_PushButton)
        self.D4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D4_PushButton.setGeometry(QtCore.QRect(170, 90, 31, 31))
        self.D4_PushButton.setText("")
        self.D4_PushButton.setCheckable(True)
        self.D4_PushButton.setAutoDefault(False)
        self.D4_PushButton.setObjectName("D4_PushButton")
        self.buttonGroup.addButton(self.D4_PushButton)
        self.B2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B2_PushButton.setGeometry(QtCore.QRect(80, 190, 31, 31))
        self.B2_PushButton.setText("")
        self.B2_PushButton.setCheckable(True)
        self.B2_PushButton.setAutoDefault(False)
        self.B2_PushButton.setObjectName("B2_PushButton")
        self.buttonGroup.addButton(self.B2_PushButton)
        self.C5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C5_PushButton.setGeometry(QtCore.QRect(210, 140, 31, 31))
        self.C5_PushButton.setText("")
        self.C5_PushButton.setCheckable(True)
        self.C5_PushButton.setAutoDefault(False)
        self.C5_PushButton.setObjectName("C5_PushButton")
        self.buttonGroup.addButton(self.C5_PushButton)
        self.B6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B6_PushButton.setGeometry(QtCore.QRect(250, 190, 31, 31))
        self.B6_PushButton.setText("")
        self.B6_PushButton.setCheckable(True)
        self.B6_PushButton.setAutoDefault(False)
        self.B6_PushButton.setObjectName("B6_PushButton")
        self.buttonGroup.addButton(self.B6_PushButton)
        self.D2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D2_PushButton.setGeometry(QtCore.QRect(80, 90, 31, 31))
        self.D2_PushButton.setText("")
        self.D2_PushButton.setAutoDefault(False)
        self.D2_PushButton.setObjectName("D2_PushButton")
        self.buttonGroup.addButton(self.D2_PushButton)
        self.Cancel_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.Cancel_PushButton.setGeometry(QtCore.QRect(190, 350, 81, 31))
        self.Cancel_PushButton.setObjectName("Cancel_PushButton")
        self.E6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E6_PushButton.setGeometry(QtCore.QRect(250, 40, 31, 31))
        self.E6_PushButton.setText("")
        self.E6_PushButton.setCheckable(True)
        self.E6_PushButton.setAutoDefault(False)
        self.E6_PushButton.setObjectName("E6_PushButton")
        self.buttonGroup.addButton(self.E6_PushButton)
        self.E3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E3_PushButton.setGeometry(QtCore.QRect(120, 40, 31, 31))
        self.E3_PushButton.setText("")
        self.E3_PushButton.setCheckable(True)
        self.E3_PushButton.setAutoDefault(False)
        self.E3_PushButton.setObjectName("E3_PushButton")
        self.buttonGroup.addButton(self.E3_PushButton)
        self.row6_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row6_Label.setGeometry(QtCore.QRect(260, 10, 31, 20))
        self.row6_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row6_Label.setObjectName("row6_Label")
        self.A1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A1_PushButton.setGeometry(QtCore.QRect(40, 240, 31, 31))
        self.A1_PushButton.setText("")
        self.A1_PushButton.setCheckable(True)
        self.A1_PushButton.setAutoDefault(False)
        self.A1_PushButton.setObjectName("A1_PushButton")
        self.buttonGroup.addButton(self.A1_PushButton)
        self.A5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A5_PushButton.setGeometry(QtCore.QRect(210, 240, 31, 31))
        self.A5_PushButton.setText("")
        self.A5_PushButton.setCheckable(True)
        self.A5_PushButton.setAutoDefault(False)
        self.A5_PushButton.setObjectName("A5_PushButton")
        self.buttonGroup.addButton(self.A5_PushButton)
        self.C4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C4_PushButton.setGeometry(QtCore.QRect(170, 140, 31, 31))
        self.C4_PushButton.setText("")
        self.C4_PushButton.setCheckable(True)
        self.C4_PushButton.setChecked(False)
        self.C4_PushButton.setAutoDefault(False)
        self.C4_PushButton.setObjectName("C4_PushButton")
        self.buttonGroup.addButton(self.C4_PushButton)
        self.D3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D3_PushButton.setGeometry(QtCore.QRect(120, 90, 31, 31))
        self.D3_PushButton.setText("")
        self.D3_PushButton.setCheckable(True)
        self.D3_PushButton.setAutoDefault(False)
        self.D3_PushButton.setObjectName("D3_PushButton")
        self.buttonGroup.addButton(self.D3_PushButton)
        self.B4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B4_PushButton.setGeometry(QtCore.QRect(170, 190, 31, 31))
        self.B4_PushButton.setText("")
        self.B4_PushButton.setCheckable(True)
        self.B4_PushButton.setAutoDefault(False)
        self.B4_PushButton.setObjectName("B4_PushButton")
        self.buttonGroup.addButton(self.B4_PushButton)
        self.A2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A2_PushButton.setGeometry(QtCore.QRect(80, 240, 31, 31))
        self.A2_PushButton.setText("")
        self.A2_PushButton.setCheckable(True)
        self.A2_PushButton.setAutoDefault(False)
        self.A2_PushButton.setObjectName("A2_PushButton")
        self.buttonGroup.addButton(self.A2_PushButton)
        self.D6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D6_PushButton.setGeometry(QtCore.QRect(250, 90, 31, 31))
        self.D6_PushButton.setText("")
        self.D6_PushButton.setCheckable(True)
        self.D6_PushButton.setAutoDefault(False)
        self.D6_PushButton.setObjectName("D6_PushButton")
        self.buttonGroup.addButton(self.D6_PushButton)
        self.E1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E1_PushButton.setGeometry(QtCore.QRect(40, 40, 31, 31))
        self.E1_PushButton.setText("")
        self.E1_PushButton.setCheckable(True)
        self.E1_PushButton.setAutoDefault(False)
        self.E1_PushButton.setFlat(False)
        self.E1_PushButton.setObjectName("E1_PushButton")
        self.buttonGroup.addButton(self.E1_PushButton)
        self.C6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C6_PushButton.setGeometry(QtCore.QRect(250, 140, 31, 31))
        self.C6_PushButton.setText("")
        self.C6_PushButton.setCheckable(True)
        self.C6_PushButton.setAutoDefault(False)
        self.C6_PushButton.setObjectName("C6_PushButton")
        self.buttonGroup.addButton(self.C6_PushButton)
        self.E2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E2_PushButton.setGeometry(QtCore.QRect(80, 40, 31, 31))
        self.E2_PushButton.setText("")
        self.E2_PushButton.setCheckable(True)
        self.E2_PushButton.setAutoDefault(False)
        self.E2_PushButton.setObjectName("E2_PushButton")
        self.buttonGroup.addButton(self.E2_PushButton)
        self.D5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D5_PushButton.setGeometry(QtCore.QRect(210, 90, 31, 31))
        self.D5_PushButton.setText("")
        self.D5_PushButton.setCheckable(True)
        self.D5_PushButton.setAutoDefault(False)
        self.D5_PushButton.setObjectName("D5_PushButton")
        self.buttonGroup.addButton(self.D5_PushButton)
        self.row1_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row1_Label.setGeometry(QtCore.QRect(50, 10, 21, 20))
        self.row1_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row1_Label.setObjectName("row1_Label")
        self.B3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B3_PushButton.setGeometry(QtCore.QRect(120, 190, 31, 31))
        self.B3_PushButton.setText("")
        self.B3_PushButton.setCheckable(True)
        self.B3_PushButton.setAutoDefault(False)
        self.B3_PushButton.setObjectName("B3_PushButton")
        self.buttonGroup.addButton(self.B3_PushButton)
        self.lineA_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineA_Label.setGeometry(QtCore.QRect(20, 240, 21, 20))
        self.lineA_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineA_Label.setObjectName("lineA_Label")
        self.E4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E4_PushButton.setGeometry(QtCore.QRect(170, 40, 31, 31))
        self.E4_PushButton.setText("")
        self.E4_PushButton.setCheckable(True)
        self.E4_PushButton.setAutoDefault(False)
        self.E4_PushButton.setObjectName("E4_PushButton")
        self.buttonGroup.addButton(self.E4_PushButton)
        self.screen_label = QtWidgets.QLabel(SeatMap_Dialog)
        self.screen_label.setGeometry(QtCore.QRect(50, 290, 221, 21))
        self.screen_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.screen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.screen_label.setObjectName("screen_label")
        self.selectedseat_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.selectedseat_Label.setGeometry(QtCore.QRect(20, 320, 271, 21))
        self.selectedseat_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedseat_Label.setObjectName("selectedseat_Label")

        self.retranslateUi(SeatMap_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SeatMap_Dialog)

    def retranslateUi(self, SeatMap_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SeatMap_Dialog.setWindowTitle(_translate("SeatMap_Dialog", "SeatMap"))
        self.lineB_Label_2.setText(_translate("SeatMap_Dialog", "B"))
        self.lineE_Label_2.setText(_translate("SeatMap_Dialog", "E"))
        self.lineD_Label_4.setText(_translate("SeatMap_Dialog", "D"))
        self.row5_Label.setText(_translate("SeatMap_Dialog", "5"))
        self.row4_Label.setText(_translate("SeatMap_Dialog", "4"))
        self.lineC_Label_3.setText(_translate("SeatMap_Dialog", "C"))
        self.Continue_PushButton.setText(_translate("SeatMap_Dialog", "Continue"))
        self.row3_Label.setText(_translate("SeatMap_Dialog", "3"))
        self.row2_Label.setText(_translate("SeatMap_Dialog", "2"))
        self.Cancel_PushButton.setText(_translate("SeatMap_Dialog", "Cancel"))
        self.row6_Label.setText(_translate("SeatMap_Dialog", "6"))
        self.row1_Label.setText(_translate("SeatMap_Dialog", "1"))
        self.lineA_Label.setText(_translate("SeatMap_Dialog", "A"))
        self.screen_label.setText(_translate("SeatMap_Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Screen</span></p></body></html>"))
        self.selectedseat_Label.setText(_translate("SeatMap_Dialog", "Unclickable seats = unavaliable"))

