# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeatMap_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeatMap_Dialog(object):
    def setupUi(self, SeatMap_Dialog):
        SeatMap_Dialog.setObjectName("SeatMap_Dialog")
        SeatMap_Dialog.resize(310, 373)
        self.lineB_Label_2 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineB_Label_2.setGeometry(QtCore.QRect(20, 190, 21, 20))
        self.lineB_Label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineB_Label_2.setObjectName("lineB_Label_2")
        self.B5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B5_PushButton.setGeometry(QtCore.QRect(210, 190, 31, 23))
        self.B5_PushButton.setText("")
        self.B5_PushButton.setObjectName("B5_PushButton")
        self.D1_PushButton_2 = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D1_PushButton_2.setGeometry(QtCore.QRect(40, 90, 31, 23))
        self.D1_PushButton_2.setText("")
        self.D1_PushButton_2.setObjectName("D1_PushButton_2")
        self.E5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E5_PushButton.setGeometry(QtCore.QRect(210, 40, 31, 23))
        self.E5_PushButton.setText("")
        self.E5_PushButton.setObjectName("E5_PushButton")
        self.A6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A6_PushButton.setGeometry(QtCore.QRect(250, 240, 31, 23))
        self.A6_PushButton.setText("")
        self.A6_PushButton.setObjectName("A6_PushButton")
        self.lineE_Label_2 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineE_Label_2.setGeometry(QtCore.QRect(20, 40, 21, 20))
        self.lineE_Label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineE_Label_2.setObjectName("lineE_Label_2")
        self.C1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C1_PushButton.setGeometry(QtCore.QRect(40, 140, 31, 23))
        self.C1_PushButton.setText("")
        self.C1_PushButton.setObjectName("C1_PushButton")
        self.lineD_Label_4 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineD_Label_4.setGeometry(QtCore.QRect(20, 90, 21, 20))
        self.lineD_Label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineD_Label_4.setObjectName("lineD_Label_4")
        self.row5_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row5_Label.setGeometry(QtCore.QRect(220, 10, 21, 20))
        self.row5_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row5_Label.setObjectName("row5_Label")
        self.row4_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row4_Label.setGeometry(QtCore.QRect(180, 10, 21, 20))
        self.row4_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row4_Label.setObjectName("row4_Label")
        self.lineC_Label_3 = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineC_Label_3.setGeometry(QtCore.QRect(20, 140, 21, 20))
        self.lineC_Label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineC_Label_3.setObjectName("lineC_Label_3")
        self.Continue_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.Continue_PushButton.setGeometry(QtCore.QRect(60, 340, 81, 23))
        self.Continue_PushButton.setObjectName("Continue_PushButton")
        self.C2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C2_PushButton.setGeometry(QtCore.QRect(80, 140, 31, 23))
        self.C2_PushButton.setText("")
        self.C2_PushButton.setObjectName("C2_PushButton")
        self.row3_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row3_Label.setGeometry(QtCore.QRect(130, 10, 21, 20))
        self.row3_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row3_Label.setObjectName("row3_Label")
        self.A3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A3_PushButton.setGeometry(QtCore.QRect(120, 240, 31, 23))
        self.A3_PushButton.setText("")
        self.A3_PushButton.setObjectName("A3_PushButton")
        self.row2_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row2_Label.setGeometry(QtCore.QRect(90, 10, 21, 20))
        self.row2_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row2_Label.setObjectName("row2_Label")
        self.A4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A4_PushButton.setGeometry(QtCore.QRect(170, 240, 31, 23))
        self.A4_PushButton.setText("")
        self.A4_PushButton.setObjectName("A4_PushButton")
        self.C3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C3_PushButton.setGeometry(QtCore.QRect(120, 140, 31, 23))
        self.C3_PushButton.setText("")
        self.C3_PushButton.setObjectName("C3_PushButton")
        self.B1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B1_PushButton.setGeometry(QtCore.QRect(40, 190, 31, 23))
        self.B1_PushButton.setText("")
        self.B1_PushButton.setObjectName("B1_PushButton")
        self.pushButton_56 = QtWidgets.QPushButton(SeatMap_Dialog)
        self.pushButton_56.setGeometry(QtCore.QRect(170, 90, 31, 23))
        self.pushButton_56.setText("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.B2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B2_PushButton.setGeometry(QtCore.QRect(80, 190, 31, 23))
        self.B2_PushButton.setText("")
        self.B2_PushButton.setObjectName("B2_PushButton")
        self.C5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C5_PushButton.setGeometry(QtCore.QRect(210, 140, 31, 23))
        self.C5_PushButton.setText("")
        self.C5_PushButton.setObjectName("C5_PushButton")
        self.B6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B6_PushButton.setGeometry(QtCore.QRect(250, 190, 31, 23))
        self.B6_PushButton.setText("")
        self.B6_PushButton.setObjectName("B6_PushButton")
        self.D2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D2_PushButton.setGeometry(QtCore.QRect(80, 90, 31, 23))
        self.D2_PushButton.setText("")
        self.D2_PushButton.setObjectName("D2_PushButton")
        self.Cancel_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.Cancel_PushButton.setGeometry(QtCore.QRect(180, 340, 81, 23))
        self.Cancel_PushButton.setObjectName("Cancel_PushButton")
        self.E6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E6_PushButton.setGeometry(QtCore.QRect(250, 40, 31, 23))
        self.E6_PushButton.setText("")
        self.E6_PushButton.setObjectName("E6_PushButton")
        self.E3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E3_PushButton.setGeometry(QtCore.QRect(120, 40, 31, 23))
        self.E3_PushButton.setText("")
        self.E3_PushButton.setObjectName("E3_PushButton")
        self.row6_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row6_Label.setGeometry(QtCore.QRect(260, 10, 31, 20))
        self.row6_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row6_Label.setObjectName("row6_Label")
        self.A1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A1_PushButton.setGeometry(QtCore.QRect(40, 240, 31, 23))
        self.A1_PushButton.setText("")
        self.A1_PushButton.setObjectName("A1_PushButton")
        self.A5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A5_PushButton.setGeometry(QtCore.QRect(210, 240, 31, 23))
        self.A5_PushButton.setText("")
        self.A5_PushButton.setObjectName("A5_PushButton")
        self.C4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C4_PushButton.setGeometry(QtCore.QRect(170, 140, 31, 23))
        self.C4_PushButton.setText("")
        self.C4_PushButton.setObjectName("C4_PushButton")
        self.D3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D3_PushButton.setGeometry(QtCore.QRect(120, 90, 31, 23))
        self.D3_PushButton.setText("")
        self.D3_PushButton.setObjectName("D3_PushButton")
        self.B4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B4_PushButton.setGeometry(QtCore.QRect(170, 190, 31, 23))
        self.B4_PushButton.setText("")
        self.B4_PushButton.setObjectName("B4_PushButton")
        self.A2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.A2_PushButton.setGeometry(QtCore.QRect(80, 240, 31, 23))
        self.A2_PushButton.setText("")
        self.A2_PushButton.setObjectName("A2_PushButton")
        self.D6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D6_PushButton.setGeometry(QtCore.QRect(250, 90, 31, 23))
        self.D6_PushButton.setText("")
        self.D6_PushButton.setObjectName("D6_PushButton")
        self.E1_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E1_PushButton.setGeometry(QtCore.QRect(40, 40, 31, 23))
        self.E1_PushButton.setText("")
        self.E1_PushButton.setObjectName("E1_PushButton")
        self.C6_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.C6_PushButton.setGeometry(QtCore.QRect(250, 140, 31, 23))
        self.C6_PushButton.setText("")
        self.C6_PushButton.setObjectName("C6_PushButton")
        self.E2_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E2_PushButton.setGeometry(QtCore.QRect(80, 40, 31, 23))
        self.E2_PushButton.setText("")
        self.E2_PushButton.setObjectName("E2_PushButton")
        self.D5_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.D5_PushButton.setGeometry(QtCore.QRect(210, 90, 31, 23))
        self.D5_PushButton.setText("")
        self.D5_PushButton.setObjectName("D5_PushButton")
        self.row1_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.row1_Label.setGeometry(QtCore.QRect(50, 10, 21, 20))
        self.row1_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.row1_Label.setObjectName("row1_Label")
        self.B3_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.B3_PushButton.setGeometry(QtCore.QRect(120, 190, 31, 23))
        self.B3_PushButton.setText("")
        self.B3_PushButton.setObjectName("B3_PushButton")
        self.lineA_Label = QtWidgets.QLabel(SeatMap_Dialog)
        self.lineA_Label.setGeometry(QtCore.QRect(20, 240, 21, 20))
        self.lineA_Label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.lineA_Label.setObjectName("lineA_Label")
        self.E4_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.E4_PushButton.setGeometry(QtCore.QRect(170, 40, 31, 23))
        self.E4_PushButton.setText("")
        self.E4_PushButton.setObjectName("E4_PushButton")
        self.Screen_PushButton = QtWidgets.QPushButton(SeatMap_Dialog)
        self.Screen_PushButton.setGeometry(QtCore.QRect(40, 290, 241, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Screen_PushButton.setFont(font)
        self.Screen_PushButton.setStyleSheet("")
        self.Screen_PushButton.setFlat(False)
        self.Screen_PushButton.setObjectName("Screen_PushButton")

        self.retranslateUi(SeatMap_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SeatMap_Dialog)

    def retranslateUi(self, SeatMap_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SeatMap_Dialog.setWindowTitle(_translate("SeatMap_Dialog", "SeatMap"))
        self.lineB_Label_2.setText(_translate("SeatMap_Dialog", "B"))
        self.lineE_Label_2.setText(_translate("SeatMap_Dialog", "E"))
        self.lineD_Label_4.setText(_translate("SeatMap_Dialog", "D"))
        self.row5_Label.setText(_translate("SeatMap_Dialog", "5"))
        self.row4_Label.setText(_translate("SeatMap_Dialog", "4"))
        self.lineC_Label_3.setText(_translate("SeatMap_Dialog", "C"))
        self.Continue_PushButton.setText(_translate("SeatMap_Dialog", "Continue"))
        self.row3_Label.setText(_translate("SeatMap_Dialog", "3"))
        self.row2_Label.setText(_translate("SeatMap_Dialog", "2"))
        self.Cancel_PushButton.setText(_translate("SeatMap_Dialog", "Cancel"))
        self.row6_Label.setText(_translate("SeatMap_Dialog", "6"))
        self.row1_Label.setText(_translate("SeatMap_Dialog", "1"))
        self.lineA_Label.setText(_translate("SeatMap_Dialog", "A"))
        self.Screen_PushButton.setText(_translate("SeatMap_Dialog", "Screen"))

